theme_location = ["~/.local/share/anarchy/default/walker/themes/"]
theme_base = []
theme = "anarchy-default"
app_launch_prefix = "uwsm app -- "
terminal_title_flag = ""
locale = ""
monitor = ""
close_when_open = true
hotreload_theme = true
as_window = false
timeout = 0
disable_click_to_close = false
force_keyboard_focus = true

[keys]
accept_typeahead = ["tab"]
trigger_labels = "lalt"
next = ["down"]
prev = ["up"]
close = ["esc"]
remove_from_history = ["shift backspace"]
resume_query = ["ctrl r"]
toggle_exact_search = ["ctrl m"]

[keys.activation_modifiers]
keep_open = "shift"
alternate = "alt"

[list]
dynamic_sub = true
keyboard_scroll_style = "emacs"
max_entries = 50
show_initial_entries = true
single_click = true
visibility_threshold = 20
placeholder = "No Results"

[search]
argument_delimiter = "#"
placeholder = "ï€‚ Search..."
delay = 0
resume_last_query = false

[activation_mode]
labels = "jkl;asdf"

[builtins.applications]
weight = 5
name = "applications"
placeholder = "ï€‚ Search..."
prioritize_new = false
hide_actions_with_empty_query = true
context_aware = false
refresh = true
show_sub_when_single = false
show_icon_when_single = true
show_generic = true
history = false
icon = ""
hidden = true

[builtins.applications.actions]
enabled = false
hide_category = true
hide_without_query = true

[builtins.switcher]
weight = 5
name = "switcher"
placeholder = "Switcher"
prefix = "/"

[builtins.finder]
use_fd = true
fd_flags = "--ignore-vcs --type file --type directory"
cmd_alt = "xdg-open $(dirname ~/%RESULT%)"
weight = 5
name = "Finder"
placeholder = "Finder"
ignore_gitignore = true
refresh = true
concurrency = 8
show_icon_when_single = true
preview_images = true
switcher_only = true
hidden = false

[builtins.calc]
require_number = true
weight = 5
name = "Calculator"
icon = "accessories-calculator"
placeholder = "Calculator"
min_chars = 3
prefix = "="

[builtins.emojis]
exec = "wl-copy"
weight = 5
name = "Emojis"
placeholder = "Emojis"
history = true
typeahead = true
show_unqualified = false
prefix = ":"

[builtins.websearch]
keep_selection = true
weight = 5
icon = "applications-internet"
name = "Websearch"
placeholder = "Websearch"
switcher_only = true

[[builtins.websearch.entries]]
name = "Google"
url = "https://www.google.com/search?q=%TERM%"

[[builtins.websearch.entries]]
name = "DuckDuckGo"
url = "https://duckduckgo.com/?q=%TERM%"
switcher_only = true

[builtins.commands]
weight = 5
icon = "utilities-terminal"
name = "commands"
placeholder = "Commands"
switcher_only = true

[builtins.runner]
eager_loading = true
weight = 5
icon = "utilities-terminal"
name = "Runner"
placeholder = "Runner"
typeahead = true
history = true
generic_entry = false       # Generic command runner
shell_config = ""           # Path to shell to parse for aliases
refresh = true
use_fd = false
hidden = true
switcher_only = true
prefix = ">"

[builtins.dmenu]
hidden = true
enabled = false

[builtins.bookmarks]
hidden = true
enabled = false

[builtins.ai]
hidden = true
enabled = false

[builtins.window]
hidden = true
enabled = false

[builtins.clipboard]
hidden = true
enabled = false

[builtins.symbols]
hidden = true
enabled = false

[builtins.ssh]
hidden = true
enabled = false

[builtins.translation]
hidden = true
enabled = false

[builtins.custom_commands]
hidden = true
enabled = false

[builtins.hyprland_keybinds]
hidden = true
enabled = false
